version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/len_front'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
#    restart: always
    command: sh -c "npm start"
